import type { Config } from 'tailwindcss';

export default {
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: 'var(--color-primary)',
          soft: 'var(--color-primary-soft)',
          hover: 'var(--color-primary-hover)',
          active: 'var(--color-primary-active)',
          muted: 'var(--color-primary-muted)',
        },
        surface: {
          primary: 'var(--bg-primary)',
          secondary: 'var(--bg-secondary)',
          tertiary: 'var(--bg-tertiary)',
          hover: 'var(--surface-hover)',
          elevated: 'var(--surface-card-elevated)',
          overlay: 'var(--surface-overlay)',
          canvas: 'var(--surface-canvas)',
          page: 'var(--surface-page)',
          sidebar: 'var(--surface-sidebar)',
          player: 'var(--surface-player)',
          card: 'var(--surface-card)',
          dialog: 'var(--surface-dialog)',
          popover: 'var(--surface-popover)',
          dropdown: 'var(--surface-dropdown)',
          input: 'var(--surface-input)',
          interactive: 'var(--surface-interactive)',
          pressed: 'var(--surface-pressed)',
          selected: 'var(--surface-selected)',
          backdrop: 'var(--surface-backdrop)',
        },
        text: {
          primary: 'var(--text-primary)',
          secondary: 'var(--text-secondary)',
          muted: 'var(--text-muted)',
          disabled: 'var(--text-disabled)',
          inverse: 'var(--text-inverse)',
        },
        border: {
          DEFAULT: 'var(--border)',
          default: 'var(--border-default)',
          strong: 'var(--border-strong)',
          focus: 'var(--border-focus)',
        },
        action: {
          primary: 'var(--action-primary)',
          'primary-hover': 'var(--action-primary-hover)',
          'primary-active': 'var(--action-primary-active)',
          'primary-soft': 'var(--action-primary-soft)',
        },
        accent: {
          DEFAULT: 'var(--accent)',
          foreground: 'var(--accent-foreground)',
          green: 'var(--color-accent-green)',
          'green-soft': 'var(--color-accent-green-soft)',
          purple: 'var(--color-accent-purple)',
        },
        'secondary-olive': 'var(--color-secondary-olive)',
        success: 'var(--color-success)',
        error: 'var(--color-danger)',
        warning: 'var(--color-warning)',
        info: 'var(--color-info)',
        selection: 'var(--color-selection)',
        focus: 'var(--color-focus-ring)',
        playback: {
          playing: 'var(--playback-playing)',
          paused: 'var(--playback-paused)',
          queued: 'var(--playback-queued)',
          progress: 'var(--playback-progress)',
        },
      },
      fontFamily: {
        sans: ['var(--font-body)'],
        heading: ['var(--font-heading)'],
        mono: ['var(--font-mono)'],
      },
      fontSize: {
        display: ['var(--text-display)', { lineHeight: 'var(--line-height-display)', fontWeight: '700', letterSpacing: 'var(--letter-spacing-tight)' }],
        h1: ['var(--text-h1)', { lineHeight: 'var(--line-height-heading)', fontWeight: '700', letterSpacing: 'var(--letter-spacing-tight)' }],
        h2: ['var(--text-h2)', { lineHeight: 'var(--line-height-heading)', fontWeight: '600', letterSpacing: 'var(--letter-spacing-tight)' }],
        h3: ['var(--text-h3)', { lineHeight: 'var(--line-height-heading)', fontWeight: '600', letterSpacing: 'var(--letter-spacing-normal)' }],
        h4: ['var(--text-h4)', { lineHeight: 'var(--line-height-heading)', fontWeight: '600', letterSpacing: 'var(--letter-spacing-normal)' }],
        'body-lg': ['var(--text-body-lg)', { lineHeight: 'var(--line-height-body)', fontWeight: '400' }],
        body: ['var(--text-body)', { lineHeight: 'var(--line-height-body)', fontWeight: '400' }],
        'body-sm': ['var(--text-body-sm)', { lineHeight: 'var(--line-height-caption)', fontWeight: '400' }],
        caption: ['var(--text-caption)', { lineHeight: 'var(--line-height-caption)', fontWeight: '400', letterSpacing: 'var(--letter-spacing-wide)' }],
        metadata: ['var(--text-metadata)', { lineHeight: 'var(--line-height-caption)', fontWeight: '500', letterSpacing: 'var(--letter-spacing-wide)' }],
        label: ['var(--text-label)', { lineHeight: 'var(--line-height-caption)', fontWeight: '500' }],
        code: ['var(--text-code)', { lineHeight: '1.6', fontWeight: '400' }],
      },
      boxShadow: {
        xs: 'var(--shadow-xs)',
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        xl: 'var(--shadow-xl)',
        glass: 'var(--shadow-glass)',
      },
      borderRadius: {
        'radius-2': 'var(--radius-2)',
        'radius-4': 'var(--radius-4)',
        'radius-6': 'var(--radius-6)',
        'radius-8': 'var(--radius-8)',
        'radius-12': 'var(--radius-12)',
        'radius-16': 'var(--radius-16)',
        'radius-20': 'var(--radius-20)',
        'radius-24': 'var(--radius-24)',
        'radius-pill': 'var(--radius-pill)',
        'radius-circle': 'var(--radius-circle)',
      },
      maxWidth: {
        app: 'var(--container-max)',
        content: 'var(--container-content)',
      },
    },
  },
  plugins: [],
} satisfies Config;
